name: Detect drift

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # hourly
    - cron: "0 * * * *"

jobs:
  pick-out-drift-issues:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write # To close issues

    outputs:
      issues: ${{steps.pick-out-drift-issues.outputs.issues}}
      has_issues: ${{steps.pick-out-drift-issues.outputs.has_issues}}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Pick out Drift issue
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        id: pick-out-drift-issues
        with:
          action: pick-out-drift-issues
          github_token: ${{ steps.app-token.outputs.token }}

  detect-drift:
    timeout-minutes: 30
    name: "detect-drift (${{matrix.issue.target}})"

    runs-on: ${{matrix.issue.runs_on}}
    needs: pick-out-drift-issues

    permissions:
      issues: write # For github-comment and tfcmt
      contents: write # To push commits
      id-token: write # For OIDC

    if: fromJSON(needs.pick-out-drift-issues.outputs.has_issues)

    strategy:
      fail-fast: false
      matrix:
        issue: ${{fromJSON(needs.pick-out-drift-issues.outputs.issues)}}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.60.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: set-drift-env
          issue: ${{toJSON(matrix.issue)}}

      - name: Set up
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        id: setup
        with:
          action: setup
          github_token: ${{ steps.app-token.outputs.token }}

      - uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        if: steps.setup.outputs.aws_assume_role_arn != ''
        with:
          role-to-assume: ${{ steps.setup.outputs.aws_assume_role_arn }}
          role-session-name: ${{ steps.setup.outputs.aws_role_session_name }}
          aws-region: ${{ steps.setup.outputs.aws_region }}

      - name: GitHub Secrets
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        id: github-secrets
        with:
          action: output-github-secrets
          github_secrets: ${{ toJSON(secrets) }}

      - name: Terraform Init
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: terraform-init
          secrets: ${{ steps.github-secrets.outputs.secrets }}

      - name: Test
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: test
          github_token: ${{ steps.app-token.outputs.token }}

      - name: Plan
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: plan
          github_token: ${{ steps.app-token.outputs.token }}
          secrets: ${{ steps.github-secrets.outputs.secrets }}

      - name: Update Drift Issue
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        if: always()
        with:
          action: update-drift-issue
          status: ${{job.status}}
          github_token: ${{ steps.app-token.outputs.token }}
