name: Detect drift

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # hourly
    - cron: "0 * * * *"

jobs:
  pick-out-drift-issues:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write # To close issues

    outputs:
      issues: ${{steps.pick-out-drift-issues.outputs.issues}}
      has_issues: ${{steps.pick-out-drift-issues.outputs.has_issues}}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.59.0
        env:
          AQUA_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - run: tfaction pick-out-drift-issues
        id: pick-out-drift-issues
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  detect-drift:
    timeout-minutes: 30
    name: "detect-drift (${{matrix.issue.target}})"

    runs-on: ${{matrix.issue.runs_on}}
    needs: pick-out-drift-issues

    permissions:
      issues: write # For github-comment and tfcmt
      contents: write # To push commits
      id-token: write # For OIDC

    if: fromJSON(needs.pick-out-drift-issues.outputs.has_issues)

    strategy:
      fail-fast: false
      matrix:
        issue: ${{fromJSON(needs.pick-out-drift-issues.outputs.issues)}}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.59.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: suzuki-shunsuke/tfaction/set-drift-env@5d2ecf0f4898a0b3ecc6b536e9a3f4691f46bfad # v2.0.0
        with:
          issue: ${{toJSON(matrix.issue)}}

      # GitHub Secrets を TFAction に渡す Action
      - uses: suzuki-shunsuke/tfaction/js@5d2ecf0f4898a0b3ecc6b536e9a3f4691f46bfad # v2.0.0
        with:
          action: export-secrets
          secrets: ${{ toJSON(secrets) }}

      - uses: suzuki-shunsuke/tfaction/setup@5d2ecf0f4898a0b3ecc6b536e9a3f4691f46bfad # v2.0.0
        with:
          github_token: ${{ steps.app-token.outputs.token }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: suzuki-shunsuke/tfaction/test@5d2ecf0f4898a0b3ecc6b536e9a3f4691f46bfad # v2.0.0
        if: false
        with:
          github_token: ${{ steps.app-token.outputs.token }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: suzuki-shunsuke/tfaction/terraform-plan@5d2ecf0f4898a0b3ecc6b536e9a3f4691f46bfad # v2.0.0
        with:
          github_token: ${{ steps.app-token.outputs.token }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: suzuki-shunsuke/tfaction/update-drift-issue@5d2ecf0f4898a0b3ecc6b536e9a3f4691f46bfad # v2.0.0
        if: always()
        with:
          status: ${{job.status}}
          github_token: ${{ steps.app-token.outputs.token }}
