name: Create drift issues

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # daily
    - cron: "0 0 * * *"

concurrency:
  group: schedule-create-drift-issues
  cancel-in-progress: false

jobs:
  create-drift-issues:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Create drift issues
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: create-drift-issues
          github_token: ${{ steps.app-token.outputs.token }}
