name: Create drift issues

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # daily
    - cron: "0 0 * * *"

concurrency:
  group: schedule-create-drift-issues
  cancel-in-progress: false

jobs:
  create-drift-issues:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Create drift issues
        uses: suzuki-shunsuke/tfaction@0627b0a1dfec9479a3fa73a5831be7979661b7eb # v2.0.4
        with:
          action: create-drift-issues
          github_token: ${{ steps.app-token.outputs.token }}
