name: Synchronize drift issue description

on:
  issue_comment:
    types:
      - created

jobs:
  sync-issue:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: |
      !github.event.issue.pull_request && startsWith(github.event.issue.title, 'Terraform Drift (') && endsWith(github.event.issue.title, ')') && github.actor == 'shimosyan'

    permissions:
      issues: write

    steps:
      - name: Sync drift issue description
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: sync-drift-issue-description
