name: Synchronize drift issue description

on:
  issue_comment:
    types:
      - created

jobs:
  sync-issue:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: |
      !github.event.issue.pull_request && startsWith(github.event.issue.title, 'Terraform Drift (') && endsWith(github.event.issue.title, ')') && github.actor == 'shimosyan'

    permissions:
      issues: write

    steps:
      - name: Sync drift issue description
        uses: suzuki-shunsuke/tfaction@4fc32a7692e857bad031bc9e0324e7135c45742b # v2.0.6
        with:
          action: sync-drift-issue-description
