name: Synchronize drift issue description

on:
  issue_comment:
    types:
      - created

jobs:
  sync-issue:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: |
      !github.event.issue.pull_request && startsWith(github.event.issue.title, 'Terraform Drift (') && endsWith(github.event.issue.title, ')') && github.actor == 'shimosyan'

    permissions:
      issues: write

    steps:
      - name: Sync drift issue description
        uses: suzuki-shunsuke/tfaction@9b6f6fb49f27d3ff63a9b7896cd661f3b9a26955 # v2.3.1
        with:
          action: sync-drift-issue-description
