name: Terraform Pull Request

on:
  workflow_call:
    secrets:
      CLIENT_ID:
        required: true
      PRIVATE_KEY:
        required: true
      CF_ACCESS_CLIENT_ID:
        required: true
      CF_ACCESS_CLIENT_SECRET:
        required: true
      DEFAULT_ROOT_PW:
        required: true
      PM_READONLY_API_TOKEN_ID:
        required: true
      PM_READONLY_API_TOKEN_SECRET:
        required: true
      PM_WRITABLE_API_TOKEN_ID:
        required: true
      PM_WRITABLE_API_TOKEN_SECRET:
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  path-filter:
    # Get changed files to filter jobs
    timeout-minutes: 10
    outputs:
      test-files: ${{steps.changes.outputs.test-files}}
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          filters: |
            test-files:
              - .github/workflows/pull-request.yaml
              - .github/workflows/terraform**
              - .github/workflows/wc-terraform**
              - tfaction-root.yaml
              - proxmox/**
              - aqua.yaml

  terraform-plan:
    needs: path-filter
    if: needs.path-filter.outputs.test-files == 'true'
    runs-on: ubuntu-latest

    env:
      PM_HTTP_HEADERS: CF-Access-Client-Id,${{ secrets.CF_ACCESS_CLIENT_ID }},CF-Access-Client-Secret,${{ secrets.CF_ACCESS_CLIENT_SECRET }}
      TFACTION_TARGET: proxmox
      TFACTION_WORKING_DIR: proxmox
      TFACTION_JOB_TYPE: terraform

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.60.0
        env:
          AQUA_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - run: github-comment exec -- github-comment hide
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Set up
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        id: setup
        with:
          action: setup
          github_token: ${{ steps.app-token.outputs.token }}

      - uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        if: steps.setup.outputs.aws_assume_role_arn != ''
        with:
          role-to-assume: ${{ steps.setup.outputs.aws_assume_role_arn }}
          role-session-name: ${{ steps.setup.outputs.aws_role_session_name }}
          aws-region: ${{ steps.setup.outputs.aws_region }}

      - name: GitHub Secrets
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        id: github-secrets
        with:
          action: output-github-secrets
          github_secrets: ${{ toJSON(secrets) }}

      - name: Terraform Init
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: terraform-init
          secrets: ${{ steps.github-secrets.outputs.secrets }}

      - name: Test
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: test
          github_token: ${{ steps.app-token.outputs.token }}

      - name: Plan
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: plan
          github_token: ${{ steps.app-token.outputs.token }}
          secrets: ${{ steps.github-secrets.outputs.secrets }}
